### ISSUE TITLE
Some hardcoded-path files are missing

### ISSUE THREAD

**Issue by shamidreza** [wnhsu/FactorizedHierarchicalVAE#1]
Hello Wei-Ning,
Truly great job on this paper. I enjoyed reading it and listening to samples.
I am trying to run the code on TIMIT example, however some file are hardcoded. I was wondering is there a way to guide how to create those files?
/data/sls/scratch/wnhsu/vae_gan/audio_encoder/egs/timit/data/train/phn.scp
/data/sls/scratch/wnhsu/code/test_slurm.sh #this is probably environment-specific
Thanks!
Hamid

**Comment by wnhsu** [comment]
thanks for reporting bugs. pushed the fixed for phn.scp. should be working now
test_slurm.sh is my local environment testing scripts. you can just comment this line. thanks
